### ISSUE TITLE
When using rbkcli scripts on windows it fails

### ISSUE THREAD

**Issue by Bmanesco** [rubrikinc/rbkcli#21]
Running any script returns this error:

```
C:\Users\BrunoManesco-PC>rbkcli snapshot all
Traceback (most recent call last):
  File "C:\Users\BrunoManesco-PC\AppData\Local\Programs\Python\Python37\Scripts\rbkcli-script.py", line 11, in <module>
    load_entry_point('rbkcli==1.0.0b4', 'console_scripts', 'rbkcli')()
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\interface\rbk_cli.py", line 332, in main
    print(rbk_cli.execute(arg_list))
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\interface\rbk_cli.py", line 98, in execute
    return self._execute(self.args_dict, self.arg_list, self.operation)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\interface\rbk_cli.py", line 306, in _execute
    return RBK.cli_execute(args_dict, arg_list, operation)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\interface\cli.py", line 255, in cli_execute
    self.result = self.rbk_target.target.command(args=kwargs)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\core\target.py", line 136, in command
    result = self.execute(args=self.req)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\core\target.py", line 70, in execute
    return self.operations.execute(self.req)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\core\handlers\operations.py", line 201, in execute
    data=self.req.data)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\core\handlers\__init__.py", line 37, in response_wrapper
    self.text = func(self, *args, **kwargs)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\core\handlers\customizer.py", line 68, in execute_api
    return self._execute_api(args, kwargs)
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\site-packages\rbkcli\core\handlers\customizer.py", line 256, in _execute_api
    mio_commando = importlib.import_module(api['operation'])
  File "c:\users\brunomanesco-pc\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'all_snapshots'
```

Need to investigate ModuleNotFoundError: No module named 'all_snapshots' on Windows systems.

**Comment by Bmanesco** [comment]
This issue has been resolved by the following commit:
https://github.com/rubrikinc/rbkcli/commit/88425e5c749ae48f4b451d37e2d95f8c75ed96ae
